Algoritmo "endereco"
// Disciplina   : Introdução a lógica de programamção
// Professor   : Marcos Monteiro
// Autor(a)    : João Pedro Holanda Neves
// Data atual  : 03/05/2022

Var
// Seção de Declarações das variáveis
endereco : caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("Qual o seu endereço?")
leia(endereco)
escreva("Seu endereço é: ", endereco)

Fimalgoritmo