Algoritmo "multiplos-de-dois-ate-cem"
// Disciplina   : Introdução a lógica de programamção
// Professor   : Marcos Monteiro
// Autor(a)    : João Pedro Holanda Neves
// Data atual  : 03/05/2022

Var
   // Seção de Declarações das variáveis
   i: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para i de 1 ate 50 passo i + 1 faca
      escreval("2 × ", i, " = ", (2 * i))
   fimpara

Fimalgoritmo