Algoritmo "tabuada-enquanto"
// Disciplina   : Introdução a lógica de programamção
// Professor   : Marcos Monteiro
// Autor(a)    : João Pedro Holanda Neves
// Data atual  : 03/05/2022

Var
   // Seção de Declarações das variáveis
   i, n: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   i<- 1
   escreva("Digite um número: ")
   leia(n)
   enquanto i <= 10 faca
      escreval(n, " × ", i, " = ", (n * i))
      i<- i+1
   fimenquanto

Fimalgoritmo